#!/usr/bin/env python3
"""
Airtable Bases Fetcher
Fetches base schemas from specific bases and generates documentation.
"""

import os
import sys
import json
import requests
from datetime import datetime
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Base directory
BASE_DIR = Path(__file__).parent.parent
CONFIG_FILE = BASE_DIR / "config" / "integration-filters.json"
OUTPUT_FILE = BASE_DIR / "business-knowledge" / "api-integrations" / "airtable" / "bases" / "base-inventory.md"

# Airtable API endpoints
AIRTABLE_API_BASE = "https://api.airtable.com/v0"
AIRTABLE_META_API = "https://api.airtable.com/v0/meta"


def load_config():
    """Load integration filters configuration"""
    with open(CONFIG_FILE, 'r') as f:
        return json.load(f)


def get_airtable_headers():
    """Get headers for Airtable API requests"""
    pat = os.getenv('AIRTABLE_PAT')
    if not pat:
        print("❌ Error: AIRTABLE_PAT not found in .env file")
        sys.exit(1)

    return {
        'Authorization': f'Bearer {pat}',
        'Content-Type': 'application/json'
    }


def fetch_base_schema(base_id, headers):
    """Fetch schema for a specific base"""
    url = f"{AIRTABLE_META_API}/bases/{base_id}/tables"

    try:
        response = requests.get(url, headers=headers)
        response.raise_for_status()
        return response.json().get('tables', [])
    except requests.exceptions.RequestException as e:
        print(f"   ⚠️  Error fetching base {base_id}: {e}")
        return []


def fetch_bases(config):
    """Fetch base schemas for configured bases"""
    print("🔄 Fetching Airtable bases...")

    headers = get_airtable_headers()
    bases_config = config['airtable']['bases']

    all_bases = []

    for base_config in bases_config:
        base_id = base_config.get('base_id')
        base_name = base_config.get('base_name', 'Unnamed')

        if not base_id:
            print(f"   ⚠️  Skipping {base_name}: No base_id configured")
            continue

        print(f"   Fetching: {base_name} ({base_id})")

        tables = fetch_base_schema(base_id, headers)

        # Filter tables if specified
        include_tables = base_config.get('include_tables', ['all'])
        exclude_tables = base_config.get('exclude_tables', [])

        if include_tables != ['all']:
            tables = [t for t in tables if t['name'] in include_tables]

        if exclude_tables:
            tables = [t for t in tables if t['name'] not in exclude_tables]

        all_bases.append({
            'base_id': base_id,
            'base_name': base_name,
            'tables': tables,
            'table_count': len(tables)
        })

        print(f"      ✅ {len(tables)} tables")

    print(f"\n✅ Fetched {len(all_bases)} bases")
    return all_bases


def generate_markdown(bases, config):
    """Generate markdown documentation"""

    total_tables = sum(b['table_count'] for b in bases)

    md = f"""# Airtable Bases Inventory

*Last Updated: {datetime.now().strftime('%Y-%m-%d')}*
*Auto-generated by fetch-airtable-bases.py*

## Overview

This document catalogs all Airtable bases for YNA Agentic.

**Total Bases**: {len(bases)}
**Total Tables**: {total_tables}

---

## Configuration

Bases configured in `config/integration-filters.json`:
"""

    for base in bases:
        md += f"- **{base['base_name']}**: {base['table_count']} tables\n"

    md += "\n---\n\n## Base Summary\n\n"
    md += "| Base Name | Base ID | Tables | Purpose | Integrations |\n"
    md += "|-----------|---------|--------|---------|-------------|\n"

    for base in bases:
        base_name = base['base_name']
        base_id = base['base_id']
        table_count = base['table_count']
        table_names = ', '.join([t['name'] for t in base['tables'][:3]])
        if len(base['tables']) > 3:
            table_names += f", +{len(base['tables']) - 3} more"

        md += f"| {base_name} | `{base_id}` | {table_count} | {table_names} | Clay, Make.com |\n"

    md += "\n---\n\n## Detailed Base Documentation\n\n"

    # Add detailed documentation for each base
    for base in bases:
        md += f"""## Base: {base['base_name']}

**Base ID**: `{base['base_id']}`
**Tables**: {base['table_count']}
**Connected Integrations**: Clay, Make.com, [others]

### Tables in this Base

"""

        for table in base['tables']:
            table_name = table['name']
            table_id = table['id']
            field_count = len(table.get('fields', []))
            primary_field = table.get('primaryFieldId', 'Unknown')

            md += f"""#### Table: {table_name}

**Table ID**: `{table_id}`
**Primary Field**: {primary_field}
**Total Fields**: {field_count}

**Fields:**

| Field Name | Type | Description | Required |
|-----------|------|-------------|----------|
"""

            for field in table.get('fields', []):
                field_name = field.get('name', 'Unnamed')
                field_type = field.get('type', 'Unknown')
                description = field.get('description', '-')
                required = '✓' if field.get('required', False) else ''

                md += f"| {field_name} | {field_type} | {description} | {required} |\n"

            md += "\n**Common Operations:**\n"
            md += "- Create: [How records are created]\n"
            md += "- Read: [How records are queried]\n"
            md += "- Update: [What triggers updates]\n"
            md += "- Delete: [Deletion policy]\n\n"

            md += "**Automations:**\n"
            md += "- [List any Airtable automations on this table]\n\n"

            md += "**Webhooks:**\n"
            md += "- [List Make.com webhooks listening to this table]\n\n"

            md += "**Views:**\n"
            md += "- [Document important views]\n\n"

            md += "---\n\n"

    # Add integration points
    md += """## Integration Points

### Clay → Airtable

**Tables Receiving Data from Clay:**

| Airtable Base | Table | Clay Table | Sync Mode |
|--------------|-------|------------|-----------|
| CRM Main | Contacts | Lead Enrichment | Real-time |
| CRM Main | Companies | Company Research | Real-time |

### Airtable → Make.com

**Tables with Webhook Triggers:**

| Airtable Base | Table | Trigger | Make.com Scenario |
|--------------|-------|---------|-------------------|
| CRM Main | Contacts | New record | Lead Notification |
| CRM Main | Deals | Stage change | Deal Updates |

### Make.com → Airtable

**Tables Updated by Make.com:**

| Airtable Base | Table | Update Type | Source |
|--------------|-------|-------------|--------|
| Marketing Hub | Campaigns | Record creation | Scheduled |
| Support | Tickets | Status updates | Email triggers |

---

## Field Mapping Standards

See [business-knowledge/api-integrations/integration-flows/field-mapping.md](../../integration-flows/field-mapping.md) for complete field mappings across platforms.

**Key Principles:**
- Use proper field types (Email type for emails, not Text)
- Consistent naming across bases
- Required fields clearly marked
- Linked records for relationships

---

## Data Quality

### Duplicate Prevention
- Use Email as unique identifier for Contacts
- Company Domain as unique for Companies
- Deal Name + Company as unique for Deals

### Validation Rules
- Email: Must be valid email format
- Phone: Must be E.164 format
- Required fields: Cannot be empty

### Data Retention
- Active records: Keep indefinitely
- Closed Lost deals: Archive after 6 months
- Old tickets: Archive after 1 year

---

## Common Base Patterns

### CRM Main Base
**Tables**: Contacts, Companies, Deals, Activities
**Purpose**: Central customer relationship management
**Record Flow**: Contact → Company (linked) → Deal (linked)

### Marketing Hub Base
**Tables**: Campaigns, Leads, Content Calendar
**Purpose**: Marketing operations and lead tracking
**Record Flow**: Campaign → Leads (generated) → Contacts (qualified)

### Support Base
**Tables**: Tickets, Customer Feedback, Knowledge Base
**Purpose**: Customer support management
**Record Flow**: Ticket → Customer (linked) → Resolution

---

## Maintenance

**Update Frequency**: Run `python scripts/fetch-airtable-bases.py` when base structure changes

**Manual Additions**: Add automation details, webhook configurations, and notes to each table section.

**Schema Changes**: When adding/removing fields:
1. Update Airtable
2. Re-run this script
3. Update field-mapping.md
4. Update Make.com scenarios
5. Test integrations

---

*To update this file, run: `python scripts/fetch-airtable-bases.py`*
"""

    return md


def main():
    """Main execution"""
    print("=" * 60)
    print("Airtable Bases Fetcher")
    print("=" * 60)

    # Load configuration
    config = load_config()

    if not config['airtable']['enabled']:
        print("⚠️  Airtable integration is disabled in config")
        sys.exit(0)

    # Fetch bases
    bases = fetch_bases(config)

    if not bases:
        print("⚠️  No bases found")
        print("   Add base IDs to config/integration-filters.json")
        sys.exit(0)

    # Generate documentation
    markdown = generate_markdown(bases, config)

    # Write to file
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_FILE, 'w') as f:
        f.write(markdown)

    print(f"\n✅ Documentation generated: {OUTPUT_FILE}")
    print(f"   Total bases documented: {len(bases)}")
    print(f"   Total tables documented: {sum(b['table_count'] for b in bases)}")

    # Save JSON backup
    json_file = OUTPUT_FILE.parent / "bases-data.json"
    with open(json_file, 'w') as f:
        json.dump(bases, f, indent=2)

    print(f"✅ JSON backup saved: {json_file}")
    print("\n" + "=" * 60)


if __name__ == "__main__":
    main()
